
-- Inserir perguntas para as fases 41-50 (perguntas 401-500)
-- FASE 41 - Perguntas 401-410 (Doutrina Social da Igreja)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Qual encíclica do Papa Leão XIII é considerada o marco inicial da Doutrina Social da Igreja?', ARRAY['Quadragesimo Anno', 'Rerum Novarum', 'Mater et Magistra', 'Pacem in Terris'], 1, 'A encíclica Rerum Novarum (1891) do Papa Leão XIII é considerada o marco inicial da Doutrina Social da Igreja, tratando da questão operária.', 'Difícil', 'Doutrina Social', 41, 1),
('Qual é o princípio fundamental da Doutrina Social da Igreja?', ARRAY['A dignidade da pessoa humana', 'A propriedade privada', 'O lucro empresarial', 'A autoridade civil'], 0, 'O princípio fundamental da Doutrina Social da Igreja é a dignidade da pessoa humana, criada à imagem e semelhança de Deus.', 'Médio', 'Doutrina Social', 41, 2),
('O que significa o princípio da subsidiariedade?', ARRAY['Centralização do poder', 'Descentralização adequada das decisões', 'Autoritarismo estatal', 'Individualismo extremo'], 1, 'O princípio da subsidiariedade defende que as decisões devem ser tomadas no nível mais próximo possível das pessoas afetadas.', 'Difícil', 'Doutrina Social', 41, 3),
('Qual Papa escreveu a encíclica "Centesimus Annus"?', ARRAY['João Paulo II', 'Bento XVI', 'Paulo VI', 'João XXIII'], 0, 'O Papa João Paulo II escreveu a encíclica Centesimus Annus em 1991, comemorando os 100 anos da Rerum Novarum.', 'Médio', 'Doutrina Social', 41, 4),
('O que defende o princípio do bem comum?', ARRAY['Interesse individual', 'Bem de todos e de cada um', 'Lucro empresarial', 'Poder político'], 1, 'O princípio do bem comum defende o bem de todos e de cada um, pois todos somos responsáveis por todos.', 'Médio', 'Doutrina Social', 41, 5),
('Qual encíclica trata especificamente do meio ambiente?', ARRAY['Laudato Si', 'Caritas in Veritate', 'Sollicitudo Rei Socialis', 'Laborem Exercens'], 0, 'A encíclica Laudato Si do Papa Francisco trata especificamente da questão ambiental e do cuidado com a casa comum.', 'Fácil', 'Doutrina Social', 41, 6),
('O que é a opção preferencial pelos pobres?', ARRAY['Exclusão dos ricos', 'Preferência especial pelos necessitados', 'Comunismo religioso', 'Assistencialismo puro'], 1, 'A opção preferencial pelos pobres é a preferência especial que a Igreja tem pelos necessitados, seguindo o exemplo de Jesus.', 'Médio', 'Doutrina Social', 41, 7),
('Qual Papa escreveu "Populorum Progressio"?', ARRAY['Paulo VI', 'João XXIII', 'Pio XII', 'João Paulo I'], 0, 'O Papa Paulo VI escreveu a encíclica Populorum Progressio em 1967, sobre o desenvolvimento dos povos.', 'Difícil', 'Doutrina Social', 41, 8),
('O que defende o princípio da solidariedade?', ARRAY['Individualismo', 'Interdependência e responsabilidade mútua', 'Competição selvagem', 'Isolamento social'], 1, 'O princípio da solidariedade defende a interdependência e responsabilidade mútua entre todas as pessoas e povos.', 'Médio', 'Doutrina Social', 41, 9),
('Qual documento do Concílio Vaticano II trata da Igreja no mundo contemporâneo?', ARRAY['Lumen Gentium', 'Gaudium et Spes', 'Dei Verbum', 'Sacrosanctum Concilium'], 1, 'A constituição pastoral Gaudium et Spes trata da Igreja no mundo contemporâneo e suas questões sociais.', 'Difícil', 'Doutrina Social', 41, 10);

-- FASE 42 - Perguntas 411-420 (Liturgia e Ano Litúrgico)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Quantos tempos tem o Ano Litúrgico?', ARRAY['4', '5', '6', '7'], 2, 'O Ano Litúrgico tem 6 tempos: Advento, Natal, Quaresma, Tríduo Pascal, Páscoa e Tempo Comum.', 'Médio', 'Liturgia', 42, 1),
('Qual cor litúrgica é usada no Advento?', ARRAY['Branco', 'Vermelho', 'Roxo', 'Verde'], 2, 'A cor litúrgica do Advento é roxa, simbolizando penitência e preparação para o Natal.', 'Fácil', 'Liturgia', 42, 2),
('Quantos domingos tem o Advento?', ARRAY['3', '4', '5', '6'], 1, 'O tempo do Advento tem 4 domingos, preparando para a celebração do Natal.', 'Fácil', 'Liturgia', 42, 3),
('Qual é a cor litúrgica do Tempo Comum?', ARRAY['Verde', 'Branco', 'Vermelho', 'Roxo'], 0, 'A cor litúrgica do Tempo Comum é verde, simbolizando esperança e crescimento na fé.', 'Fácil', 'Liturgia', 42, 4),
('Quantos dias dura a Quaresma?', ARRAY['30', '40', '50', '60'], 1, 'A Quaresma dura 40 dias, preparando os fiéis para a celebração da Páscoa.', 'Fácil', 'Liturgia', 42, 5),
('Qual cor se usa na Quarta-feira de Cinzas?', ARRAY['Roxo', 'Preto', 'Cinza', 'Branco'], 0, 'Na Quarta-feira de Cinzas usa-se a cor roxa, marcando o início da Quaresma.', 'Médio', 'Liturgia', 42, 6),
('O que significa a palavra "liturgia"?', ARRAY['Oração privada', 'Obra do povo', 'Canto sagrado', 'Leitura bíblica'], 1, 'Liturgia significa "obra do povo", sendo a participação de todo o povo de Deus no culto divino.', 'Médio', 'Liturgia', 42, 7),
('Qual é o ciclo de leituras bíblicas da Missa?', ARRAY['2 anos', '3 anos', '4 anos', '5 anos'], 1, 'O ciclo de leituras da Missa é de 3 anos (A, B, C), garantindo maior variedade de textos bíblicos.', 'Difícil', 'Liturgia', 42, 8),
('Em que dia começa o Ano Litúrgico?', ARRAY['1º de janeiro', 'Domingo de Ramos', 'Primeiro domingo do Advento', 'Domingo de Pentecostes'], 2, 'O Ano Litúrgico começa no primeiro domingo do Advento, preparando para o Natal.', 'Médio', 'Liturgia', 42, 9),
('Qual cor litúrgica representa o martírio?', ARRAY['Roxo', 'Vermelho', 'Preto', 'Dourado'], 1, 'A cor vermelha representa o martírio e o derramamento de sangue pelos mártires da fé.', 'Médio', 'Liturgia', 42, 10);

-- FASE 43 - Perguntas 421-430 (Mariologia - Dogmas Marianos)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Quantos dogmas marianos existem?', ARRAY['2', '3', '4', '5'], 2, 'Existem 4 dogmas marianos: Maternidade Divina, Virgindade Perpétua, Imaculada Conceição e Assunção.', 'Médio', 'Mariologia', 43, 1),
('Em que concílio foi definido o dogma da Maternidade Divina?', ARRAY['Niceia', 'Constantinopla', 'Éfeso', 'Calcedônia'], 2, 'O dogma da Maternidade Divina de Maria foi definido no Concílio de Éfeso em 431.', 'Difícil', 'Mariologia', 43, 2),
('Quem definiu o dogma da Imaculada Conceição?', ARRAY['Pio IX', 'Pio XII', 'Leão XIII', 'João XXIII'], 0, 'O Papa Pio IX definiu o dogma da Imaculada Conceição em 1854, através da bula Ineffabilis Deus.', 'Difícil', 'Mariologia', 43, 3),
('Em que ano foi definido o dogma da Assunção?', ARRAY['1950', '1854', '1870', '1929'], 0, 'O dogma da Assunção foi definido pelo Papa Pio XII em 1950, através da constituição Munificentissimus Deus.', 'Difícil', 'Mariologia', 43, 4),
('O que significa "Theotokos"?', ARRAY['Mãe de Jesus', 'Mãe de Deus', 'Virgem Maria', 'Senhora Nossa'], 1, 'Theotokos significa "Mãe de Deus", título definido no Concílio de Éfeso para Maria.', 'Difícil', 'Mariologia', 43, 5),
('Qual aparição de Maria foi reconhecida primeiro pela Igreja?', ARRAY['Fátima', 'Lourdes', 'Guadalupe', 'La Salette'], 2, 'A aparição de Nossa Senhora de Guadalupe (1531) foi a primeira aparição mariana reconhecida oficialmente pela Igreja.', 'Difícil', 'Mariologia', 43, 6),
('O que celebramos no dia 8 de dezembro?', ARRAY['Anunciação', 'Imaculada Conceição', 'Assunção', 'Natividade de Maria'], 1, 'No dia 8 de dezembro celebramos a Imaculada Conceição de Maria, definida como dogma em 1854.', 'Médio', 'Mariologia', 43, 7),
('Qual é o significado da Assunção de Maria?', ARRAY['Sua morte natural', 'Sua elevação corporal ao céu', 'Sua ressurreição', 'Sua canonização'], 1, 'A Assunção significa que Maria foi elevada de corpo e alma ao céu, sem passar pela corrupção do sepulcro.', 'Médio', 'Mariologia', 43, 8),
('Em Fátima, quantas aparições Maria fez às crianças?', ARRAY['5', '6', '7', '8'], 1, 'Em Fátima, Nossa Senhora apareceu 6 vezes às três crianças pastorinhas entre maio e outubro de 1917.', 'Médio', 'Mariologia', 43, 9),
('Qual oração mariana foi ensinada pelo anjo em Fátima?', ARRAY['Ave Maria', 'Salve Rainha', 'Oração do Anjo', 'Magnificat'], 2, 'O anjo ensinou às crianças a "Oração do Anjo": "Meu Deus, eu creio, adoro, espero e amo-Vos..."', 'Difícil', 'Mariologia', 43, 10);

-- FASE 44 - Perguntas 431-440 (Santos Padres da Igreja)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Quem é conhecido como o "Doutor da Graça"?', ARRAY['Santo Agostinho', 'São Jerônimo', 'São João Crisóstomo', 'Santo Ambrósio'], 0, 'Santo Agostinho é conhecido como "Doutor da Graça" por seus escritos sobre a graça divina e predestinação.', 'Difícil', 'Patrística', 44, 1),
('Qual Padre da Igreja traduziu a Bíblia para o latim?', ARRAY['Santo Agostinho', 'São Jerônimo', 'São João Damasceno', 'Santo Atanásio'], 1, 'São Jerônimo traduziu a Bíblia para o latim, criando a Vulgata, versão oficial da Igreja por séculos.', 'Médio', 'Patrística', 44, 2),
('Quem é chamado "Boca de Ouro"?', ARRAY['São Basílio', 'São Gregório Nazianzeno', 'São João Crisóstomo', 'São Gregório de Nissa'], 2, 'São João Crisóstomo é chamado "Boca de Ouro" (Crisóstomo) por sua extraordinária eloquência na pregação.', 'Difícil', 'Patrística', 44, 3),
('Qual obra famosa escreveu Santo Agostinho?', ARRAY['Suma Teológica', 'Confissões', 'Contra Celso', 'Didaquê'], 1, 'Santo Agostinho escreveu as "Confissões", uma das obras mais importantes da literatura cristã.', 'Médio', 'Patrística', 44, 4),
('Quem defendeu a divindade de Cristo contra o arianismo?', ARRAY['Santo Atanásio', 'Orígenes', 'Tertuliano', 'São Cipriano'], 0, 'Santo Atanásio defendeu vigorosamente a divindade de Cristo contra a heresia ariana.', 'Difícil', 'Patrística', 44, 5),
('Qual dos Padres Capadócios era irmão de São Basílio?', ARRAY['São Gregório Nazianzeno', 'São Gregório de Nissa', 'São João Crisóstomo', 'Santo Atanásio'], 1, 'São Gregório de Nissa era irmão de São Basílio Magno, ambos Padres Capadócios.', 'Difícil', 'Patrística', 44, 6),
('Quem escreveu "A Cidade de Deus"?', ARRAY['São Jerônimo', 'Santo Agostinho', 'Santo Ambrósio', 'São João Crisóstomo'], 1, 'Santo Agostinho escreveu "A Cidade de Deus" como resposta às acusações contra o cristianismo após a queda de Roma.', 'Médio', 'Patrística', 44, 7),
('Qual Padre da Igreja foi bispo de Milão?', ARRAY['Santo Ambrósio', 'São Jerônimo', 'Santo Agostinho', 'São Basílio'], 0, 'Santo Ambrósio foi bispo de Milão e teve grande influência na conversão de Santo Agostinho.', 'Médio', 'Patrística', 44, 8),
('Quem foi o primeiro a usar o termo "Trindade"?', ARRAY['Tertuliano', 'Orígenes', 'Santo Agostinho', 'São Justino'], 0, 'Tertuliano foi o primeiro a usar o termo "Trindade" (Trinitas) para se referir ao mistério das três Pessoas divinas.', 'Difícil', 'Patrística', 44, 9),
('Qual Padre oriental defendeu o uso das imagens sagradas?', ARRAY['São João Damasceno', 'São Basílio', 'São Gregório Nazianzeno', 'Santo Atanásio'], 0, 'São João Damasceno defendeu o uso das imagens sagradas contra a heresia iconoclasta.', 'Difícil', 'Patrística', 44, 10);

-- FASE 45 - Perguntas 441-450 (História da Salvação)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Com quem Deus fez a primeira aliança?', ARRAY['Adão', 'Noé', 'Abraão', 'Moisés'], 1, 'Deus fez a primeira aliança com Noé após o dilúvio, prometendo não mais destruir a terra pelas águas.', 'Médio', 'História da Salvação', 45, 1),
('Qual é o sinal da aliança com Noé?', ARRAY['Circuncisão', 'Arco-íris', 'Cordeiro', 'Pedras'], 1, 'O arco-íris é o sinal da aliança entre Deus e Noé, prometendo não mais destruir a terra pelo dilúvio.', 'Fácil', 'História da Salvação', 45, 2),
('A quem Deus prometeu uma descendência numerosa como as estrelas?', ARRAY['Noé', 'Abraão', 'Isaac', 'Jacó'], 1, 'Deus prometeu a Abraão uma descendência numerosa como as estrelas do céu e a areia do mar.', 'Fácil', 'História da Salvação', 45, 3),
('Qual é o sinal da aliança com Abraão?', ARRAY['Arco-íris', 'Circuncisão', 'Cordeiro', 'Altar'], 1, 'A circuncisão é o sinal da aliança entre Deus e Abraão e sua descendência.', 'Médio', 'História da Salvação', 45, 4),
('Em que monte Abraão foi provado por Deus?', ARRAY['Sinai', 'Moriá', 'Carmelo', 'Horeb'], 1, 'No monte Moriá, Deus provou a fé de Abraão pedindo-lhe para sacrificar Isaac.', 'Difícil', 'História da Salvação', 45, 5),
('Quantos anos o povo hebreu permaneceu no Egito?', ARRAY['400', '430', '440', '450'], 1, 'O povo hebreu permaneceu 430 anos no Egito, conforme registrado em Êxodo 12,40.', 'Difícil', 'História da Salvação', 45, 6),
('Em que monte Moisés recebeu os Dez Mandamentos?', ARRAY['Moriá', 'Sinai', 'Carmelo', 'Sião'], 1, 'Moisés recebeu os Dez Mandamentos no monte Sinai, selando a aliança com o povo de Israel.', 'Fácil', 'História da Salvação', 45, 7),
('Quantos anos o povo de Israel peregrinou no deserto?', ARRAY['30', '40', '50', '60'], 1, 'O povo de Israel peregrinou 40 anos no deserto antes de entrar na Terra Prometida.', 'Fácil', 'História da Salvação', 45, 8),
('Quem foi o sucessor de Moisés?', ARRAY['Aarão', 'Josué', 'Caleb', 'Eleazar'], 1, 'Josué foi o sucessor de Moisés e conduziu o povo de Israel para a conquista da Terra Prometida.', 'Médio', 'História da Salvação', 45, 9),
('Qual rei unificou as doze tribos de Israel?', ARRAY['Saul', 'Davi', 'Salomão', 'Samuel'], 1, 'O rei Davi unificou as doze tribos de Israel e estabeleceu Jerusalém como capital do reino.', 'Médio', 'História da Salvação', 45, 10);

-- FASE 46 - Perguntas 451-460 (Teologia Fundamental)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('O que significa a palavra "revelação"?', ARRAY['Descoberta humana', 'Manifestação divina', 'Experiência mística', 'Conhecimento filosófico'], 1, 'Revelação significa manifestação divina, quando Deus se dá a conhecer ao ser humano.', 'Médio', 'Teologia Fundamental', 46, 1),
('Quais são as duas formas da Revelação divina?', ARRAY['Natural e sobrenatural', 'Pública e privada', 'Antiga e nova', 'Oral e escrita'], 1, 'As duas formas da Revelação são pública (para toda a humanidade) e privada (para pessoas específicas).', 'Difícil', 'Teologia Fundamental', 46, 2),
('Quando se encerrou a Revelação pública?', ARRAY['Com Moisés', 'Com os profetas', 'Com a morte do último apóstolo', 'Com o Concílio de Trento'], 2, 'A Revelação pública se encerrou com a morte do último apóstolo, sendo Cristo a plenitude da Revelação.', 'Difícil', 'Teologia Fundamental', 46, 3),
('O que é o Depósito da Fé?', ARRAY['Dinheiro da Igreja', 'Conjunto da Revelação', 'Arquivo secreto', 'Tesouro artístico'], 1, 'O Depósito da Fé é o conjunto da Revelação divina confiado à Igreja para ser guardado e transmitido.', 'Médio', 'Teologia Fundamental', 46, 4),
('Quem é o intérprete autêntico da Revelação?', ARRAY['Os teólogos', 'O Magistério da Igreja', 'Os santos', 'Os bispos individualmente'], 1, 'O Magistério da Igreja é o intérprete autêntico da Revelação, guiado pelo Espírito Santo.', 'Médio', 'Teologia Fundamental', 46, 5),
('O que são as "fontes da Revelação"?', ARRAY['Escritura e Tradição', 'Antigo e Novo Testamento', 'Evangelhos e cartas', 'Concílios e encíclicas'], 0, 'As fontes da Revelação são a Sagrada Escritura e a Sagrada Tradição, que formam um único depósito.', 'Médio', 'Teologia Fundamental', 46, 6),
('O que é a inspiração bíblica?', ARRAY['Criatividade humana', 'Ação do Espírito Santo', 'Sabedoria natural', 'Experiência religiosa'], 1, 'A inspiração bíblica é a ação do Espírito Santo que move os autores sagrados a escrever a Palavra de Deus.', 'Médio', 'Teologia Fundamental', 46, 7),
('O que significa "inerrância bíblica"?', ARRAY['Perfeição literária', 'Ausência de erros na verdade salvífica', 'Conhecimento científico', 'Precisão histórica'], 1, 'Inerrância bíblica significa que a Escritura não contém erros nas verdades que Deus quis revelar para nossa salvação.', 'Difícil', 'Teologia Fundamental', 46, 8),
('Qual é a relação entre fé e razão?', ARRAY['Oposição total', 'Harmonia e complementaridade', 'Identidade perfeita', 'Indiferença mútua'], 1, 'Fé e razão são harmônicas e complementares, pois ambas vêm de Deus e não podem se contradizer.', 'Difícil', 'Teologia Fundamental', 46, 9),
('O que é a analogia da fé?', ARRAY['Comparação com outras religiões', 'Coerência interna da Revelação', 'Método científico', 'Técnica literária'], 1, 'A analogia da fé é a coerência interna das verdades reveladas, que se iluminam mutuamente.', 'Difícil', 'Teologia Fundamental', 46, 10);

-- FASE 47 - Perguntas 461-470 (Escatologia)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('O que significa "escatologia"?', ARRAY['Estudo dos santos', 'Doutrina sobre as últimas coisas', 'História da Igreja', 'Liturgia oriental'], 1, 'Escatologia é a doutrina sobre as últimas coisas: morte, juízo, céu, inferno e ressurreição.', 'Médio', 'Escatologia', 47, 1),
('Quais são as "quatro últimas coisas"?', ARRAY['Morte, juízo, céu, inferno', 'Fé, esperança, caridade, justiça', 'Nascimento, vida, morte, ressurreição', 'Terra, água, ar, fogo'], 0, 'As quatro últimas coisas são: morte, juízo (particular e final), céu e inferno.', 'Médio', 'Escatologia', 47, 2),
('O que acontece na morte segundo a fé católica?', ARRAY['Fim absoluto', 'Separação da alma do corpo', 'Reencarnação', 'Sono eterno'], 1, 'Na morte ocorre a separação da alma imortal do corpo, que aguarda a ressurreição final.', 'Médio', 'Escatologia', 47, 3),
('O que é o juízo particular?', ARRAY['Julgamento dos outros', 'Juízo imediatamente após a morte', 'Exame de consciência', 'Confissão sacramental'], 1, 'O juízo particular é o julgamento que cada alma recebe imediatamente após a morte.', 'Médio', 'Escatologia', 47, 4),
('Quando acontecerá o juízo final?', ARRAY['Após cada morte', 'No fim dos tempos', 'A cada século', 'Nunca acontecerá'], 1, 'O juízo final acontecerá no fim dos tempos, quando Cristo voltar em glória.', 'Fácil', 'Escatologia', 47, 5),
('O que é o purgatório?', ARRAY['Lugar de punição eterna', 'Estado de purificação', 'Segunda chance na terra', 'Limbo das crianças'], 1, 'O purgatório é o estado de purificação final antes de entrar na glória do céu.', 'Médio', 'Escatologia', 47, 6),
('O que é a visão beatífica?', ARRAY['Visão da terra', 'Contemplação direta de Deus', 'Sonho celestial', 'Memória do passado'], 1, 'A visão beatífica é a contemplação direta de Deus, que constitui a felicidade eterna do céu.', 'Difícil', 'Escatologia', 47, 7),
('O que caracteriza o inferno?', ARRAY['Fogo material', 'Separação eterna de Deus', 'Aniquilação da alma', 'Sofrimento temporário'], 1, 'O inferno é caracterizado pela separação eterna de Deus, fonte de toda felicidade.', 'Médio', 'Escatologia', 47, 8),
('O que é a ressurreição da carne?', ARRAY['Volta à vida terrena', 'Reunião da alma com o corpo glorificado', 'Reencarnação', 'Cura das doenças'], 1, 'A ressurreição da carne é a reunião da alma com o corpo glorificado no fim dos tempos.', 'Médio', 'Escatologia', 47, 9),
('Qual é a oração tradicional pelos mortos?', ARRAY['Pai Nosso', 'Ave Maria', 'Eterno descanso', 'Gloria ao Pai'], 2, 'A oração "Eterno descanso" é a oração tradicional da Igreja pelos fiéis defuntos.', 'Fácil', 'Escatologia', 47, 10);

-- FASE 48 - Perguntas 471-480 (Catecismo da Igreja Católica)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Em que ano foi promulgado o atual Catecismo da Igreja Católica?', ARRAY['1985', '1992', '1997', '2000'], 1, 'O Catecismo da Igreja Católica foi promulgado pelo Papa João Paulo II em 1992.', 'Difícil', 'Catecismo', 48, 1),
('Quantas partes tem o Catecismo da Igreja Católica?', ARRAY['3', '4', '5', '6'], 1, 'O Catecismo tem 4 partes: Credo, Sacramentos, Vida em Cristo e Oração Cristã.', 'Médio', 'Catecismo', 48, 2),
('Qual parte do Catecismo trata da oração?', ARRAY['Primeira', 'Segunda', 'Terceira', 'Quarta'], 3, 'A quarta parte do Catecismo trata da oração cristã, tendo como centro o Pai Nosso.', 'Médio', 'Catecismo', 48, 3),
('O que trata a primeira parte do Catecismo?', ARRAY['Sacramentos', 'A profissão de fé', 'Mandamentos', 'Oração'], 1, 'A primeira parte trata da profissão de fé, comentando o Credo Apostólico.', 'Fácil', 'Catecismo', 48, 4),
('Quantos artigos tem o Credo Apostólico?', ARRAY['10', '11', '12', '13'], 2, 'O Credo Apostólico tem 12 artigos, que resumem as principais verdades da fé católica.', 'Médio', 'Catecismo', 48, 5),
('Qual é o primeiro mandamento da Igreja?', ARRAY['Participar da Missa dominical', 'Jejuar e abster-se', 'Confessar os pecados', 'Comungar na Páscoa'], 0, 'O primeiro mandamento da Igreja é participar da Missa nos domingos e festas de preceito.', 'Médio', 'Catecismo', 48, 6),
('Quantos mandamentos da Igreja existem?', ARRAY['4', '5', '6', '7'], 1, 'Existem 5 mandamentos da Igreja, que especificam o mínimo para a vida cristã.', 'Médio', 'Catecismo', 48, 7),
('O que são as obras de misericórdia corporais?', ARRAY['6', '7', '8', '9'], 1, 'São 7 obras de misericórdia corporais: dar de comer, beber, vestir, visitar, curar, resgatar e sepultar.', 'Médio', 'Catecismo', 48, 8),
('Quantas são as obras de misericórdia espirituais?', ARRAY['6', '7', '8', '9'], 1, 'São 7 obras de misericórdia espirituais, que cuidam das necessidades da alma.', 'Médio', 'Catecismo', 48, 9),
('Qual é a oração modelo de todo cristão?', ARRAY['Ave Maria', 'Pai Nosso', 'Glória', 'Credo'], 1, 'O Pai Nosso é a oração modelo de todo cristão, ensinada pelo próprio Jesus.', 'Fácil', 'Catecismo', 48, 10);

-- FASE 49 - Perguntas 481-490 (Concílios Ecumênicos)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('Quantos Concílios Ecumênicos reconhece a Igreja Católica?', ARRAY['20', '21', '22', '23'], 1, 'A Igreja Católica reconhece 21 Concílios Ecumênicos, sendo o último o Vaticano II.', 'Difícil', 'Concílios', 49, 1),
('Qual foi o primeiro Concílio Ecumênico?', ARRAY['Constantinopla I', 'Niceia I', 'Éfeso', 'Calcedônia'], 1, 'O primeiro Concílio Ecumênico foi Niceia I (325), que condenou o arianismo.', 'Médio', 'Concílios', 49, 2),
('O que definiu o Concílio de Niceia I?', ARRAY['Divindade do Espírito Santo', 'Divindade de Cristo', 'Maternidade divina de Maria', 'Canon bíblico'], 1, 'Niceia I definiu a divindade de Cristo contra a heresia ariana, formulando o Credo Niceno.', 'Médio', 'Concílios', 49, 3),
('Em que concílio foi definida a Maternidade Divina de Maria?', ARRAY['Niceia I', 'Constantinopla I', 'Éfeso', 'Calcedônia'], 2, 'O Concílio de Éfeso (431) definiu Maria como Theotokos (Mãe de Deus).', 'Difícil', 'Concílios', 49, 4),
('O que definiu o Concílio de Calcedônia?', ARRAY['Duas naturezas em Cristo', 'Trindade', 'Sacramentos', 'Papado'], 0, 'Calcedônia (451) definiu que Cristo tem duas naturezas (divina e humana) em uma só pessoa.', 'Difícil', 'Concílios', 49, 5),
('Qual concílio condenou definitivamente a iconoclastia?', ARRAY['Niceia I', 'Niceia II', 'Constantinopla IV', 'Latrão I'], 1, 'Niceia II (787) condenou a iconoclastia e defendeu a veneração das imagens sagradas.', 'Difícil', 'Concílios', 49, 6),
('Em que anos aconteceu o Concílio Vaticano I?', ARRAY['1869-1870', '1870-1871', '1871-1872', '1868-1869'], 0, 'O Concílio Vaticano I aconteceu entre 1869-1870, definindo a infalibilidade papal.', 'Difícil', 'Concílios', 49, 7),
('O que definiu o Vaticano I sobre o Papa?', ARRAY['Primazia', 'Infalibilidade', 'Celibato', 'Sucessão apostólica'], 1, 'O Vaticano I definiu a infalibilidade papal quando fala ex cathedra sobre fé e moral.', 'Médio', 'Concílios', 49, 8),
('Em que anos aconteceu o Vaticano II?', ARRAY['1962-1965', '1960-1963', '1963-1966', '1961-1964'], 0, 'O Concílio Vaticano II aconteceu entre 1962-1965, promovendo a renovação da Igreja.', 'Médio', 'Concílios', 49, 9),
('Qual Papa convocou o Concílio Vaticano II?', ARRAY['Pio XII', 'João XXIII', 'Paulo VI', 'João Paulo I'], 1, 'O Papa João XXIII convocou o Concílio Vaticano II em 1962.', 'Médio', 'Concílios', 49, 10);

-- FASE 50 - Perguntas 491-500 (Espiritualidade Católica)
INSERT INTO public.quiz_questions (question, options, correct_answer, explanation, difficulty, category, phase, question_order) VALUES
('O que são as três vias da vida espiritual?', ARRAY['Fé, esperança, caridade', 'Purgativa, iluminativa, unitiva', 'Oração, jejum, esmola', 'Lectio, meditatio, contemplatio'], 1, 'As três vias são: purgativa (purificação), iluminativa (iluminação) e unitiva (união com Deus).', 'Difícil', 'Espiritualidade', 50, 1),
('O que é a "lectio divina"?', ARRAY['Leitura científica', 'Leitura orante da Escritura', 'Estudo teológico', 'Leitura literária'], 1, 'Lectio divina é a leitura orante da Sagrada Escritura, método tradicional de oração.', 'Médio', 'Espiritualidade', 50, 2),
('Quantos mistérios tem o Santo Rosário tradicional?', ARRAY['15', '20', '25', '30'], 1, 'O Santo Rosário tradicional tem 20 mistérios: 5 gozosos, 5 dolorosos, 5 gloriosos e 5 luminosos.', 'Médio', 'Espiritualidade', 50, 3),
('Quem acrescentou os mistérios luminosos ao Rosário?', ARRAY['João Paulo II', 'Bento XVI', 'Paulo VI', 'João XXIII'], 0, 'O Papa João Paulo II acrescentou os mistérios luminosos em 2002.', 'Médio', 'Espiritualidade', 50, 4),
('O que é a Adoração Eucarística?', ARRAY['Comunhão frequente', 'Oração diante do Santíssimo', 'Missa diária', 'Jejum eucarístico'], 1, 'A Adoração Eucarística é a oração contemplativa diante de Jesus presente na Eucaristia.', 'Fácil', 'Espiritualidade', 50, 5),
('O que significa "oração mental"?', ARRAY['Pensar em Deus', 'Oração silenciosa do coração', 'Memorizar orações', 'Leitura de livros'], 1, 'Oração mental é a oração silenciosa do coração, diálogo íntimo com Deus.', 'Médio', 'Espiritualidade', 50, 6),
('Qual é a oração própria do tempo da Quaresma?', ARRAY['Via Sacra', 'Rosário', 'Terço', 'Angelus'], 0, 'A Via Sacra é a oração própria da Quaresma, meditando a Paixão de Cristo.', 'Fácil', 'Espiritualidade', 50, 7),
('O que são as devoções populares?', ARRAY['Superstições', 'Expressões da fé do povo', 'Liturgia oficial', 'Tradições folclóricas'], 1, 'As devoções populares são expressões autênticas da fé do povo, aprovadas pela Igreja.', 'Médio', 'Espiritualidade', 50, 8),
('O que é o exame de consciência?', ARRAY['Confissão pública', 'Revisão da vida espiritual', 'Psicologia religiosa', 'Direção espiritual'], 1, 'O exame de consciência é a revisão da vida espiritual, preparação para a confissão.', 'Fácil', 'Espiritualidade', 50, 9),
('Qual é o objetivo da vida espiritual católica?', ARRAY['Felicidade terrena', 'Santidade e união com Deus', 'Sucesso material', 'Reconhecimento social'], 1, 'O objetivo da vida espiritual católica é a santidade e a união íntima com Deus.', 'Médio', 'Espiritualidade', 50, 10);
